package com.payment.merchant.domain;

import com.payment.common.core.error.BizException;
import com.payment.common.core.error.ErrorCodes;

/**
 * Merchant aggregate root.
 *
 * <p>State transitions are ONLY exposed through the explicit state-machine methods
 * ({@link #approve()}, {@link #suspend()}, {@link #terminate()}). There is no public
 * setter for {@code status} or {@code settlementEligible}; illegal transitions throw
 * {@link BizException} with {@link ErrorCodes#STATE_TRANSITION_VIOLATION}.
 */
public class Merchant {

    private Long id;
    private final String merchantCode;
    private final String name;
    private MerchantStatus status;
    private final String settlementAccountRef;
    private boolean settlementEligible;

    public Merchant(String merchantCode, String name, String settlementAccountRef) {
        this.merchantCode = merchantCode;
        this.name = name;
        this.settlementAccountRef = settlementAccountRef;
        this.status = MerchantStatus.PENDING_REVIEW;
        this.settlementEligible = false;
    }

    /**
     * Assigned by the repository on persistence. Mutable only because the id is
     * generated by the infra layer; no other field is externally settable.
     */
    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public String getMerchantCode() {
        return merchantCode;
    }

    public String getName() {
        return name;
    }

    public MerchantStatus getStatus() {
        return status;
    }

    public String getSettlementAccountRef() {
        return settlementAccountRef;
    }

    public boolean isSettlementEligible() {
        return settlementEligible;
    }

    /**
     * PENDING_REVIEW or SUSPENDED -> ACTIVE, and marks the merchant eligible for settlement.
     */
    public void approve() {
        if (status != MerchantStatus.PENDING_REVIEW && status != MerchantStatus.SUSPENDED) {
            throw BizException.of(ErrorCodes.STATE_TRANSITION_VIOLATION,
                    "Cannot approve merchant in status " + status);
        }
        this.status = MerchantStatus.ACTIVE;
        this.settlementEligible = true;
    }

    /**
     * ACTIVE -> SUSPENDED. {@code settlementEligible} is left untouched, but the merchant
     * is no longer eligible for settlement because eligibility also requires status == ACTIVE.
     */
    public void suspend() {
        if (status != MerchantStatus.ACTIVE) {
            throw BizException.of(ErrorCodes.STATE_TRANSITION_VIOLATION,
                    "Cannot suspend merchant in status " + status);
        }
        this.status = MerchantStatus.SUSPENDED;
    }

    /**
     * Any state (except TERMINATED) -> TERMINATED. Terminal: a second call throws.
     */
    public void terminate() {
        if (status == MerchantStatus.TERMINATED) {
            throw BizException.of(ErrorCodes.STATE_TRANSITION_VIOLATION,
                    "Merchant is already terminated");
        }
        this.status = MerchantStatus.TERMINATED;
    }

    /**
     * A merchant can be settled only while ACTIVE and explicitly marked eligible.
     */
    public boolean isEligibleForSettlement() {
        return status == MerchantStatus.ACTIVE && settlementEligible;
    }
}
